import { iconSvg } from "./icons";

// word -> embedded picture data URL, generated by AI per book theme.
export type ObjectAssets = Record<string, string>;

// Draws an object centered at (cx, cy): an AI picture when one was generated for
// the word, otherwise the built-in line icon (so the free path still works).
export function drawObject(
  objects: ObjectAssets | undefined,
  word: string,
  cx: number,
  cy: number,
  size: number,
  sw = 3,
): string {
  const url = objects?.[word.toLowerCase()];
  if (url) {
    const x = (cx - size / 2).toFixed(1);
    const y = (cy - size / 2).toFixed(1);
    const s = size.toFixed(1);
    return `<image href="${url}" x="${x}" y="${y}" width="${s}" height="${s}" preserveAspectRatio="xMidYMid meet"/>`;
  }
  return iconSvg(word, cx, cy, size, sw);
}
